apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 15672 
      protocol: TCP
  selector:
    components: {{ .Values.rabbitmq.components }}