apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.name }}-secret
type: Opaque
data:
  SEED_USERNAME: ZGVtbw==
  SEED_USER_PASSWORD: ZGVtbw==
  AMQP_EXCHANGE: ZGVtbw==
  AMQP_USER: ZGVtbw==
  AMQP_PASSWORD: ZGVtbw==
  AMQP_HOSTNAME: ZGVtbw==
  AMQP_QUEUE: ZGVtbw==